name: tana_web_commerce
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.0
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  smooth_page_indicator: ^1.2.0+3
  badges: ^3.1.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_background: "assets/icon/background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/logo2.png
